version: '3.8'

services:
  mysqldb:
    container_name: mysql_container
    image: mysql:8.0
    volumes:
      - /var/lib/docker/volumes/87b0991257035c8f1267c65c2a2355d6d44ff15b3705bf1f2c1cad61e0ad8159/_data
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employee_management_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  employee-management:
    image: employee-management:latest
    container_name: employee-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/employee_management_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge