version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employee_management_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  employee-management:
    image: employee-management:latest
    container_name: employee-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/employee_management_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge